### ISSUE TITLE
Rule usage poll

### ISSUE THREAD

**Issue by cartant** [cartant/eslint-plugin-rxjs#1]
Eventually, when I have the time, I'm planning on porting the non-legacy rules in [`rxjs-tslint-rules`](https://github.com/cartant/rxjs-tslint-rules) to ESLint - adding them to the rules in this repo.

ATM, I've just ported two rules: one that doesn't need type information; and one that does.

The sensible approach would be to port the most frequently used rules first. However, I don't have stats for rule usage. If you use the rules, please post a comment below containing the names of those that you use - not the full configurations; just the rule names, please.

**Comment by cartant** [comment]
@felixfbecker ^

**Comment by adrianfaciu** [comment]
rxjs-no-unsafe-takeuntil
rxjs-no-unsafe-first
rxjs-no-unsafe-catch
rxjs-no-unbound-methods
rxjs-no-internal
rxjs-no-ignored-subscribe
rxjs-no-unsafe-switchmap

**Comment by felixfbecker** [comment]
- rxjs-no-nested-subscribe
- rxjs-throw-error
- rxjs-no-ignored-subscription
- rxjs-no-async-subscribe
- rxjs-no-ignored-observable
- rxjs-no-unbound-methods

(in order of importance)

**Comment by DPros** [comment]
rxjs-no-exposed-subjects
rxjs-no-ignored-replay-buffer

**Comment by awk** [comment]
I'm specifically interested in

- rxjs-no-unsafe-takeuntil

I'll see if I can do it myself using a fork from this repo, and give you a PR?

**Comment by cartant** [comment]
@awk

> I'll see if I can do it myself using a fork from this repo, and give you a PR?

Of course! Thanks.

**Comment by yannickglt** [comment]
rxjs-deep-operators
rxjs-no-internal
rxjs-no-subject-value

**Comment by attilacsanyi** [comment]
rxjs-no-subject-unsubscribe
rxjs-no-unsafe-switchmap
rxjs-no-unsafe-takeuntil
rxjs-no-nested-subscribe
rxjs-ban-observables
rxjs-ban-operators

Cheers!

**Comment by awk** [comment]
So… my needs 'took a turn' and I've been looking at the 'no-patched' rule in rxjs-tslint-rules and I've become very stuck down a whole trying to get the type checking services to yield the underlying type of a symbol.

Specifically in the test cases there's a test to look for `source.filter(…)` - I cannot for the life of me establish the type of `source` using typeChecker etc. (working from the existing no-connectable rule in this repo).

I feel like this rule needs to establish that the type of `source` is `Observable` - in order to then fail (because `filter` is a known patched operator). However I'm stuck :-(

Any suggestions greatly appreciated - https://gist.github.com/awk/fed5266c44c929d6a28ac762b1a9c324

**Comment by cartant** [comment]
> I've been looking at the 'no-patched' rule

For the record, I have no intention of porting any of the v5-only or v5-related rules to ESLint.

**Comment by awk** [comment]
Fair enough - I ended up in this quagmire because I'm trying to move some code away from patched operators to using `.pipe()` - so that I can then move to V6 :-)

I'll probably run TSLint over the code to catch the patched operators, fix them, then move on with ESLint (which we've already adopted generally).

**Comment by timdeschryver** [comment]
Fyi, each rule requested in this issue has been migrated or has a PR open.

**Comment by cartant** [comment]
Thanks for the awesome work, @timdeschryver

I'll publish a beta soon. I promise.

**Comment by cartant** [comment]
FYI, version `0.0.1-beta.1` has just been publish. IIRC, it contains all of the rules mentioned in this issue and a few more. To see what has been converted and what remains, have a look at #7.
