### ISSUE TITLE
no-ignored-subscription with take, takeUntil operators

### ISSUE THREAD

**Issue by unlight** [cartant/eslint-plugin-rxjs#39]
Consider this code (Angular component)

```ts
    ngOnInit() {
        this.activatedRoute.params
            .pipe(
                takeUntil(this.destroy$),
            )
            .subscribe(() => {
            });
    }
```

rxjs/no-ignored-subscription is fired, but I do not need to unsubscribe if I'm using `takeUntil` or `take` operators. 

https://blog.codecentric.de/en/2018/01/different-ways-unsubscribing-rxjs-observables-angular/

Can you add option to not fire `no-ignored-subscription` rule if `takeUntil` or `take` are exists in the pipe?

**Comment by cartant** [comment]
I'm going to say "no" for the following reasons:

* It makes the rule far more complicated. And it depends upon where the `takeUntil` is in the `pipe`. If there is a flattening operator after the `takeUntil`, there is no guarantee the composed observable will complete.
* It's not a general solution and adding this to the rule invites requests for further special handling of observables that complete.
* You can easily disable the rule on a per-use basis using one of the ESLint comment flags.
* IMO, explicit `subscribe` calls like this - and explicit `subscribe` calls in general - are uncommon in Angular applications. (It has been some time since I worked with Angular, but, IIRC, the last NgRx-based application I worked with had no explicit `subscribe` calls.)
* And - lastly and most interestingly - one of the things that might happen with RxJS is that the type system might be used to 'brand' observables that are known to complete. If this does happen, then the rule could be updated to ignore `subscribe` calls made on observables 'branded' as completing.
