### ISSUE TITLE
[no-subject-value] why using `value` or `getValue` is an anti pattern?

### ISSUE THREAD

**Issue by fytriht** [cartant/eslint-plugin-rxjs#72]
https://github.com/cartant/eslint-plugin-rxjs/blob/main/docs/rules/no-subject-value.md

**Comment by cartant** [comment]
It's an anti-pattern because using the property - or method - involves using imperative rather than reactive code. I was going to say that the `value` property and `getValue` method aren't going to be removed or anything - they'll remain part of the API - and that's why this rule isn't in the recommended configuration ... but it is. That's an oversight. It shouldn't have been recommended, as it's rather opinionated - my preference is for consumers interested in a subject's value to obtain it _only_ via subscriptions.

Anyway, I've removed the rule from the recommended configuration. If you are using `value`/`getValue` and have no concern with mixing imperative and reactive code, then you have nothing to worry about.
