### ISSUE TITLE
Error evaluating no-unsafe-subject-next

### ISSUE THREAD

**Issue by rubenhelsloot** [cartant/eslint-plugin-rxjs#76]
Hi, first of all, awesome work on the plugin!

I'm trying to configure it for my project, but when I enable the recommended rules, the linter errors on the rule `no-unsafe-subject-next`. It throws the following error:

```
TypeError: typeChecker.getTypeArguments is not a function or its return value is not iterable
Occurred while linting /Users/rubenhelsloot/crunchr/static/ng/components/widgets/base/widget.component.ts:73
    at CallExpression[callee.property.name='next'] (/Users/rubenhelsloot/crunchr/node_modules/eslint-plugin-rxjs/dist/rules/no-unsafe-subject-next.js:32:55)
    at /Users/rubenhelsloot/crunchr/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/rubenhelsloot/crunchr/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/rubenhelsloot/crunchr/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/rubenhelsloot/crunchr/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/rubenhelsloot/crunchr/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/rubenhelsloot/crunchr/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
    at /Users/rubenhelsloot/crunchr/node_modules/eslint/lib/linter/linter.js:936:32
    at Array.forEach (<anonymous>)
```

The relevant line is an Angular component:

```
  ngOnDestroy() {
    this.destroy$.next();
  }
```

Where the subject `destroy$` is initialised as `protected readonly destroy$ = new Subject();`.
I think it might be caused by it not having a type, but when I add the type, it still throws the same error.

I'm disabling the rule for now, so I can use the rest of this plugin.

Thanks in advance!

**Comment by cartant** [comment]
I added a test case for the usage you mention and the versions and configuration used in this package's tests work just fine:

https://github.com/cartant/eslint-plugin-rxjs/blob/e2f21633d8669d5feca0d4f4b8c242069941792a/tests/rules/no-unsafe-subject-next.ts#L64-L71

If a type parameter is not specified in the constructor call, the subject's element type will default to `unknown`. And the rule implementation specifically handles `unknown` and won't effect an error in that case:

https://github.com/cartant/eslint-plugin-rxjs/blob/e2f21633d8669d5feca0d4f4b8c242069941792a/source/rules/no-unsafe-subject-next.ts#L49-L51

Why you get an error, IDK. Maybe because you are using an older version of TypeScript or have a different ESLint configuration.

Also, in RxJS version 7, you'll get a TypeScript error, as `next()` will only be legal for `void` subjects - e.g. `new Subject<void>()`.

**Comment by rubenhelsloot** [comment]
Interesting, thank you for your time!

**Comment by mhenke** [comment]
What was the resolution? I am having the same issue.

Angular CLI: 8.3.29
Node: 16.13.0
OS: win32 x64
Angular: 8.2.14
... common, compiler, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic, router, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.29
@angular-devkit/build-angular      0.803.29
@angular-devkit/build-ng-packagr   0.803.29
@angular-devkit/build-optimizer    0.803.29
@angular-devkit/build-webpack      0.803.29
@angular-devkit/core               8.3.29
@angular-devkit/schematics         15.0.4
@angular/animations                8.2.9
@angular/cdk                       8.2.3
@angular/cli                       8.3.29
@angular/forms                     8.2.9
@angular/material                  8.2.3
@ngtools/webpack                   8.3.29
@schematics/angular                14.2.10
@schematics/update                 0.803.29
ng-packagr                         5.7.1
rxjs                               6.5.5
typescript                         3.5.3
webpack                            4.39.2

**Comment by rubenhelsloot** [comment]
I think I ended up disabling the rule and keeping the rest of the plugin as-is

**Comment by mhenke** [comment]
I updated typescript and the issue seems fixed
