### ISSUE TITLE
The rule `no-internal` catches `rxjs/internal-compatibility` as well

### ISSUE THREAD

**Issue by aerabi** [cartant/eslint-plugin-rxjs#80]
I believe this rule exists to avoid importing things from `rxjs/internal/*` because they are also exposed on the `rxjs` level. But in the case of `fromPromise` (which lives under `rxjs/internal-compatibility`) there is no alternative: it is not exported on the main level.

The regex should match `rxjs/internal/` and not `rxjs/internal`.

**Comment by cartant** [comment]
IIRC, `rxjs/internal-compatibility` is also an internal location. It's used - in v6 - via `rxjs-compat` and isn't intended for direct use. If you've used it in v6, it'll break in v7 because support for  `rxjs-compat` - a v5/v6 compatibility helper - was removed in v7 (along with the `rxjs/internal-compatibility` location).

**Comment by aerabi** [comment]
Thanks for the quick response. You're right. I guess `from` should be used instead. I'll close the issue then.
